apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/instance: default
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: devfileregistry-operator
    app.kubernetes.io/part-of: devfileregistry-operator
    app.kubernetes.io/managed-by: kustomize
  name: default
  namespace: system
