apiVersion: registry.devfile.io/v1alpha1
kind: DevfileRegistry
metadata:
  name: devfileregistry-sample
spec:
  bootstrapImage: quay.io/devfile/metadata-server:latest
  ociRegistryImage: registry:latest